replicaCount: 1

service:
  type: NodePort
  port: 80

image:
  repository: textaitestcontainerregistery.azurecr.io/ner-service
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: acr-secrets

containerPort: 8000